### ISSUE TITLE
order.txt

### ISSUE THREAD

**Issue by GaoJunruo** [THUwangcy/SLRC#3]
Hello, I download the order.txt and wonder if a user buys different items at the same timestamp and different users buy items at different timestamps?

**Comment by THUwangcy** [comment]
I'm not sure I understand the question. A user may buy items at either the same timestamp (a basket) or different timestamps. Different users also have chances to buy items at the same timestamp (they may happen to consume items at different places with exactly the same time)

**Comment by GaoJunruo** [comment]
Thanks for your reply very much. I’m just new to this direction and unfamiliar with the conception. I thought the timestamps are the specific time, so I'm confused about why a user can buy different items at the same time. 
e.g. 
u0	i0	4	1520316742
u0	i1	4	1520316742
u0	i2	4	1520316742
u0	i3	4	1520316742

**Comment by THUwangcy** [comment]
This is an offline shopping dataset. The timestamp here is the time of checking out, which means users could choose a basket of items and then check out at the same time (just like we do in the supermarket).

**Comment by GaoJunruo** [comment]
Thanks! I've got it! Besides, if a user buys only one item at each timestamp, the ground truth is only one item, instead of a list of items. Is it right? 
e.g.
u0 i0 4 1520316743
u0 i1 4 1520316744
u0 i2 4 1520316745
u0 i3 4 1520316746

**Comment by THUwangcy** [comment]
Yes, exactly:)

**Comment by GaoJunruo** [comment]
Thanks very much!
